#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# sos installation
python -m sos_notebook.install
jupyter labextension install jupyterlab-sos --no-build 

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build 
jupyter labextension install beakerx-jupyterlab --no-build 

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc --no-build 

# Jupyter/Jupyterlab extension for proxying internal applications
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install jupyterlab-server-proxy --no-build 

# Building everything up
jupyter lab build --dev

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local


###############################################################
#             mysql/mariadb-related commands                  #
###############################################################

# export MARIADB_VERSION=10.4.6
# echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.bashrc
# echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.profile

# export MARIADB_HOME=$(pwd)/mariadb-${MARIADB_VERSION}
# echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.bashrc
# echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.profile

# wget http://mirror.ufscar.br/mariadb//mariadb-${MARIADB_VERSION}/bintar-linux-glibc_214-x86_64/mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz -q  && \
# tar -xvf mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz >> /dev/null  && \
# rm mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz                     && \
# mv mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64 mariadb-${MARIADB_VERSION} 

# # adding bin/ to $path
# echo "export PATH=\$PATH:\$MARIADB_HOME/bin"     >> ~/.bashrc
# echo "export PATH=\$PATH:\$MARIADB_HOME/bin"     >> ~/.profile

###############################################################
#             mysql minimal-related commands                  #
###############################################################

export MYSQL_VERSION=8.0.17
echo "export MYSQL_VERSION=${MYSQL_VERSION}" >> ~/.bashrc
echo "export MYSQL_VERSION=${MYSQL_VERSION}" >> ~/.profile

export MYSQL_HOME=$(pwd)/mysql-${MYSQL_VERSION}
echo "export MYSQL_HOME=${MYSQL_HOME}"       >> ~/.bashrc
echo "export MYSQL_HOME=${MYSQL_HOME}"       >> ~/.profile

       
wget https://cdn.mysql.com/archives/mysql-8.0/mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz -q  && \
tar -xf mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz >> /dev/null                                && \
rm      mysql-${MYSQL_VERSION}-linux-x86_64-minimal.tar.xz                                             && \
mv      mysql-${MYSQL_VERSION}-linux-x86_64-minimal        mysql-${MYSQL_VERSION} 

# adding bin/ to $path
echo "export PATH=\$PATH:\$MYSQL_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$MYSQL_HOME/bin"   >> ~/.profile


