#!/bin/bash


chmod +x ~/binder/start.mysql 
#chmod +x ~/binder/start.mariadb 

# starting mysql in parallel
~/binder/start.mysql   &


code-server --install-extension formulahendry.vscode-mysql
code-server --install-extension jakebathman.mysql-syntax
code-server --install-extension mtxr.sqltools
code-server .  --auth none &



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"